export type Startup = {
  name: string;
  company: string;
  sector: string;
  description: string;
  photo: string;
};

/** AUSCEP startup directory. Photos hotlink ASME's own Webflow CDN for now. */
export const startups: Startup[] = [
  { name: "Alexandra Hu", company: "Skan", sector: "Healthcare Tech", description: "Automated skin lesion detection for melanoma screening", photo: "/startups/1.jpg" },
  { name: "Anne Stephenson", company: "IMG Communication Coaching", sector: "Medical Education", description: "Communication training for international medical graduates", photo: "/startups/2.jpg" },
  { name: "Benjamin Gold", company: "Medical Support Solutions (Vascutherm 5)", sector: "MedTech", description: "Mobile compression and cooling/heating device", photo: "/startups/3.jpg" },
  { name: "Birinder Giddey", company: "AeroHealth Link", sector: "HealthTech", description: "Drone logistics for rural pathology and medicine transport", photo: "/startups/4.jpg" },
  { name: "Brenda Taylor", company: "Focus Forward Courses", sector: "Mental Health EdTech", description: "ADHD education for newly diagnosed adults", photo: "/startups/5.jpg" },
  { name: "Brett Sacks", company: "Snap Log", sector: "MedTech", description: "Encrypted surgical logbook with OCR technology", photo: "/startups/6.jpg" },
  { name: "Caitlin Hitchcock", company: "Memory Flexibility (MemFlex)", sector: "Mental Health Tech", description: "Intervention for mental health treatment advancement", photo: "/startups/7.jpeg" },
  { name: "Cameron Grayden", company: "Aeris", sector: "MedTech", description: "Endotracheal intubation safety improvement device", photo: "/startups/8.jpeg" },
  { name: "Catherene Pham", company: "Bio-Ti Implants", sector: "Biotech", description: "4D bio-printed titanium implants for drug delivery", photo: "/startups/9.jpg" },
  { name: "Daniel Peyton", company: "FindWays", sector: "Mental Health Platform", description: "Website for child mental health management", photo: "/startups/10.jpeg" },
  { name: "Aaron Wong", company: "AI-Powered Telehealth Solution", sector: "HealthTech", description: "Primary care AI and integrated telehealth system", photo: "/startups/11.jpeg" },
  { name: "Alex Soorbratty", company: "Papillon", sector: "MedTech", description: "Combined infusion and patient-controlled analgesic device", photo: "/startups/12.png" },
  { name: "Alwin Tan", company: "Synergy Care (VitalsVault)", sector: "Digital Health", description: "Secure multilingual health data sharing platform", photo: "/startups/13.jpg" },
  { name: "Anna Braun", company: "Medic[AI]", sector: "HealthTech", description: "AI-assisted clinical documentation system", photo: "/startups/14.jpg" },
  { name: "Anurag Ganugapati", company: "StatDoctor", sector: "HealthTech", description: "Marketplace connecting locum doctors with hospitals", photo: "/startups/15.png" },
  { name: "Aveena Anantharajah", company: "Non-invasive Ventilation Mask Tech", sector: "MedTech", description: "Innovative respiratory mask technology development", photo: "/startups/16.jpeg" },
  { name: "Monica Hadges", company: "Mi Team Mental Health", sector: "HealthTech", description: "Multi-disciplinary e-collaboration software", photo: "/startups/17.jpg" },
  { name: "Sam Donegan", company: "SupportSorted", sector: "Mental Health Platform", description: "Therapist matching and availability platform", photo: "/startups/18.jpg" },
  { name: "Elleesha King", company: "Pulse Tile", sector: "MedTech", description: "Single-use cardiac arrest detection device", photo: "/startups/19.jpg" },
  { name: "Ettie Ben-Shabat", company: "Neuro Rehab Training Platform", sector: "MedTech / Education", description: "Brain imaging extraction for neurological rehab", photo: "/startups/20.jpeg" },
  { name: "Fabrizzio Horta", company: "InnovaIVF.ai", sector: "Biotech / HealthTech", description: "AI-powered fertility and IVF technology", photo: "/startups/21.jpeg" },
  { name: "Fiona Brownfoot", company: "Kali Healthcare", sector: "MedTech", description: "Fetal monitoring device with lab development team", photo: "/startups/22.png" },
  { name: "Forbes McGain", company: "ReResp", sector: "Sustainability / MedTech", description: "Reusable N95 mask for environmental sustainability", photo: "/startups/23.jpeg" },
  { name: "Francis Lai", company: "CosMe", sector: "HealthTech", description: "Skincare allergen avoidance app", photo: "/startups/24.jpeg" },
  { name: "Geoffrey Toogood", company: "CRAZYSOCKS4DOCS", sector: "Mental Health Charity", description: "Healthcare worker mental health charity initiative", photo: "/startups/25.jpg" },
  { name: "Gillian Singleton", company: "In2health", sector: "Prevention Platform", description: "Prevention-focused health solutions", photo: "/startups/26.jpeg" },
  { name: "Hanumanth Swaroop", company: "Medical Employment Center", sector: "HealthTech", description: "Doctor recruitment and employment platform", photo: "/startups/27.jpg" },
  { name: "Helen Frazer", company: "AI Breast Cancer Screening", sector: "HealthTech / AI", description: "Artificial intelligence for breast cancer detection", photo: "/startups/28.jpeg" },
  { name: "Henry Howard", company: "Lister Health AI Scribe", sector: "HealthTech", description: "Lightweight AI scribe for healthcare professionals", photo: "/startups/29.jpg" },
  { name: "James Aridas", company: "Viventem", sector: "Maternal Health Platform", description: "Antenatal care coordination app", photo: "/startups/30.jpg" },
  { name: "Jennifer Coller", company: "Heart Health Equity Initiative", sector: "Healthcare Services", description: "Regional Victoria cardiac health support", photo: "/startups/31.jpeg" },
  { name: "Jenny Kirschner", company: "PALS", sector: "Community Health", description: "Pharmacy-led loneliness and isolation intervention", photo: "/startups/32.jpeg" },
  { name: "Jeremy Grummet", company: "MRI PRO", sector: "Medical Education", description: "Prostate MRI training program for specialists", photo: "/startups/33.jpeg" },
  { name: "Joel Monmolin", company: "SkinAware", sector: "HealthTech", description: "Personalized skin health and longevity platform", photo: "/startups/34.jpg" },
  { name: "Johannes Maehrlein", company: "You Can Fix Yourself", sector: "HealthTech", description: "Self-treatment assessment and video instruction platform", photo: "/startups/35.jpg" },
  { name: "Joseph Ischia", company: "Jiffystent", sector: "MedTech", description: "Ureteric stent insertion device", photo: "/startups/36.png" },
  { name: "Josh Szental", company: "Guide", sector: "HealthTech", description: "Clinical decision support app platform", photo: "/startups/37.jpg" },
  { name: "Jubal John", company: "Baby Portal", sector: "Pediatric Platform", description: "Secure pediatric parent-clinician communication platform", photo: "/startups/38.webp" },
  { name: "Junyi Shi", company: "TrustyDocs", sector: "HealthTech", description: "Clinician review and performance data website", photo: "/startups/39.jpg" },
  { name: "Justin Moore", company: "Coherence Health", sector: "Healthcare Services", description: "Systemic healthcare problem-solving platform", photo: "/startups/40.jpeg" },
  { name: "Justin Yeung", company: "PredicTx Colon", sector: "HealthTech / AI", description: "Chemotherapy toxicity prediction tool", photo: "/startups/41.jpeg" },
  { name: "Patrick Cao", company: "Slit-lamp Biomicroscope Adapter", sector: "MedTech", description: "Mobile phone slit-lamp adapter for optometry", photo: "/startups/42.jpg" },
  { name: "Keith Joe", company: "Wearable Vital Signs Technology", sector: "MedTech", description: "Real-time wireless vital signs monitoring", photo: "/startups/43.jpeg" },
  { name: "Lucia Chimanga", company: "CTG AI Interpretation Tool", sector: "HealthTech / AI", description: "AI cardiotocograph interpretation system", photo: "/startups/44.jpg" },
  { name: "Mark Zhong", company: "Clavian", sector: "HealthTech / AI", description: "Surgical complication detection automation", photo: "/startups/45.png" },
  { name: "Mollie McCarthy", company: "Capabl", sector: "Digital Health", description: "Chronic pain and return-to-work platform", photo: "/startups/46.jpg" },
  { name: "Mueed Mian", company: "Rarely Alone", sector: "Peer Support Platform", description: "Chronic disease peer-to-peer support app", photo: "/startups/47.jpg" },
  { name: "Nainaben Dhana", company: "Rapid Access Counselling Services", sector: "Mental Health Services", description: "Healthcare worker counseling for work challenges", photo: "/startups/48.jpg" },
  { name: "Nathan Butler", company: "Active Health", sector: "Wellness Platform", description: "Post-viral and invisible illness recovery support", photo: "/startups/49.jpeg" },
  { name: "Neville Fields", company: "Viventem", sector: "Maternal Health Platform", description: "Antenatal care coordination app", photo: "/startups/50.jpg" },
  { name: "Partha Das", company: "Mental Health Geolocation Service", sector: "HealthTech", description: "Right service-to-patient connection system", photo: "/startups/51.jpg" },
  { name: "Penelope McLernon", company: "Medical Education Platform", sector: "EdTech", description: "Animated medical education with mnemonics", photo: "/startups/52.jpg" },
  { name: "Reinhardt Verster", company: "MindMatch Australia", sector: "Mental Health Directory", description: "Comprehensive mental health service directory", photo: "/startups/53.jpg" },
  { name: "Rishabh Hariharan", company: "Journi", sector: "Research Platform", description: "AI-powered academic research workflow platform", photo: "/startups/54.jpg" },
  { name: "Sally-Anne McCormack", company: "ANTSA", sector: "Digital Mental Health", description: "AI-powered mental health tool with mood tracking", photo: "/startups/55.jpg" },
  { name: "Salwan Al-Salihi", company: "Uterine Prolapse Innovation", sector: "MedTech", description: "Surgical innovation for prolapse treatment", photo: "/startups/56.png" },
  { name: "Sanya Vallath", company: "DocTree", sector: "Career Development Platform", description: "Personalized mentoring for doctors", photo: "/startups/57.jpg" },
  { name: "Sebastian Corlette", company: "Cost-effective EEG System", sector: "MedTech", description: "Affordable pediatric EEG technology", photo: "/startups/58.png" },
  { name: "Shu Ng", company: "Integrated Smoking Cessation Service", sector: "Public Health", description: "Smoking cessation platform and support", photo: "/startups/59.jpg" },
  { name: "Sophie Tran", company: "Baby Well", sector: "Pregnancy Platform", description: "Pregnancy journey navigation tool", photo: "/startups/60.jpg" },
  { name: "Sumedha Verma", company: "Sleepnatal", sector: "Sleep Health Platform", description: "Sleep health service and training integration", photo: "/startups/61.jpg" },
  { name: "Umesh Gupta", company: "Niramaya (ZipClose)", sector: "MedTech", description: "Sutureless surgical incision closure device", photo: "/startups/62.jpg" },
  { name: "Victoria Wang", company: "AugmentHealth", sector: "HealthTech / AI", description: "Responsible AI platform for healthcare insights", photo: "/startups/63.jpg" },
  { name: "Windell Ang", company: "Connect Me", sector: "HealthTech", description: "Referrer-specialist connection platform", photo: "/startups/64.jpg" },
  { name: "Yoni Goldenberg", company: "DR.QR", sector: "Digital Health", description: "Patient medical records control and access", photo: "/startups/65.jpeg" },
  { name: "Yuri Yin-Moe Aung", company: "Journi", sector: "Research Platform", description: "AI research workflow and publication platform", photo: "/startups/66.jpg" },
  { name: "Yushy Zhou", company: "SMART Choice Tool", sector: "HealthTech / AI", description: "Knee replacement outcome prediction tool", photo: "/startups/67.jpeg" },
  { name: "Yagiz Alp Aksoy", company: "EosGene Therapeutics", sector: "Gene Therapy", description: "NanoSyringe light-activated delivery platform", photo: "/startups/68.jpg" },
  { name: "Whitney Luxford", company: "Airline Medical Clearance Solutions", sector: "Aviation Health", description: "Flight medical clearance process innovation", photo: "/startups/69.jpeg" },
  { name: "Vidhun Premkumar", company: "Neurological Exam Quantification", sector: "MedTech", description: "Objective neurological examination technology", photo: "/startups/70.jpeg" },
  { name: "Vannessa Leung", company: "Horizontal Eye Drop Aid", sector: "MedTech", description: "Ophthalmology eye drop application device", photo: "/startups/71.jpeg" },
  { name: "Tim Packer", company: "ClevaCare", sector: "HealthTech / AI", description: "Hospital bed availability and patient flow platform", photo: "/startups/72.jpg" },
  { name: "Suzanna Lindsey-Temple", company: "gene-s", sector: "Precision Medicine Platform", description: "Personalized medicine software solution", photo: "/startups/73.png" },
  { name: "Shadi Bina", company: "Flex", sector: "Admin Software", description: "Customizable workflow software for allied health", photo: "/startups/74.jpg" },
  { name: "Ryan Day", company: "HealthSpanner", sector: "Longevity Platform", description: "AI-powered genomic health and longevity insights", photo: "/startups/75.jpg" },
  { name: "Roy Mariathas", company: "Reggie", sector: "HealthTech", description: "Tech-enabled healthcare innovation platform", photo: "/startups/76.jpeg" },
  { name: "Robyn Sierla", company: "Lymbase", sector: "Clinical Support System", description: "Lymphedema clinic management software", photo: "/startups/77.jpeg" },
  { name: "Rob Tamblyn", company: "EMR Link", sector: "HealthTech", description: "Automated EMR patient data collection tool", photo: "/startups/78.jpg" },
  { name: "Ray Kelly", company: "Too Deadly For Diabetes", sector: "Community Health", description: "Diabetes management for remote communities", photo: "/startups/79.jpeg" },
  { name: "Priyamvada Sobarun", company: "UV Smartphone Camera Tech", sector: "Dermatology Tech", description: "UV camera for sunscreen application guidance", photo: "/startups/80.jpeg" },
  { name: "Peter Do", company: "EMR Application Specialist", sector: "Healthcare Tech", description: "Emergency medicine EMR consulting services", photo: "/startups/81.jpeg" },
  { name: "Penelope Maxwell", company: "Maxwell Minds", sector: "Psychiatry Support", description: "Psychiatric and pediatric medication management", photo: "/startups/82.jpg" },
  { name: "Paul Middleton", company: "Resuscitation Systems (HeartMeter)", sector: "MedTech / Training", description: "CPR training mannequin with AI feedback system", photo: "/startups/83.jpg" },
  { name: "Patrick Gough", company: "MediBetter", sector: "Healthcare Software", description: "MBS billing software for Australian health providers", photo: "/startups/84.png" },
  { name: "Padraig O'Sullivan", company: "Virtual Immersive Education", sector: "Healthcare Education", description: "VR-based nursing competency and empathy training", photo: "/startups/85.jpeg" },
  { name: "Nikhil Kumar", company: "KookaCare Air", sector: "Remote Healthcare", description: "Remote monitoring and home-based care systems", photo: "/startups/86.jpg" },
  { name: "Nathan Moore", company: "VR Healthcare Education", sector: "Healthcare Education", description: "Virtual reality clinician education platform", photo: "/startups/87.jpeg" },
  { name: "Natalie Green", company: "Bettalife Solutions", sector: "Healthcare Wellness", description: "Digital burnout and trauma support for professionals", photo: "/startups/88.jpg" },
  { name: "Morteza Aghmesheh", company: "Biodegradable Chemotherapy Implant", sector: "Oncology Biotech", description: "Polymer implant for pancreatic cancer treatment", photo: "/startups/89.png" },
  { name: "Mohammad Rabiei", company: "RapidX Diagnostic", sector: "Diagnostics", description: "Point-of-care rapid diagnostic test platform", photo: "/startups/90.jpg" },
  { name: "Mary Kaspar", company: "Likability", sector: "Mental Health Education", description: "Youth and adult relationship education program", photo: "/startups/91.png" },
  { name: "Marrianne McGhee", company: "ScrubUp Surgical Software", sector: "OR Management", description: "Surgical safety and OR productivity platform", photo: "/startups/92.jpg" },
  { name: "Laura Simmons", company: "Theratrak", sector: "Allied Health Platform", description: "Therapy collaboration and progress tracking platform", photo: "/startups/93.png" },
  { name: "Kyle Joseph", company: "Fractal Pay", sector: "FinTech / Healthcare", description: "Healthcare insurance and payment processing platform", photo: "/startups/94.png" },
  { name: "Kirsten Larven", company: "Able to Play", sector: "Disability Services", description: "Specialized sports and social skills for disabled children", photo: "/startups/95.jpg" },
  { name: "Kiran Soni", company: "Altasense", sector: "Diagnostics", description: "Novel platform diagnostic technology system", photo: "/startups/96.jpg" },
  { name: "Kazuaki Negishi", company: "MicroCavitics", sector: "Cardiology MedTech", description: "Ultrasound technique for heart attack treatment", photo: "/startups/97.jpg" },
  { name: "Joseph Grace", company: "Autologous Liquid Embolic Agents", sector: "Vascular Biotech", description: "Vascular intervention with embolic agent development", photo: "/startups/98.jpeg" },
  { name: "Jo Braid", company: "Burnout Recovery Programs", sector: "Wellness / Coaching", description: "Healthcare professional burnout recovery services", photo: "/startups/99.jpeg" },
  { name: "Jessica Theron", company: "Ella Health", sector: "Women's Health Platform", description: "Digital chronic pelvic pain management platform", photo: "/startups/100.png" },
  { name: "Jeffrey Rogers", company: "WorkWell", sector: "Occupational Health", description: "Occupational psychosocial demands profiler", photo: "/startups/101.jpg" },
  { name: "Janaki Patel", company: "Emforce Scrubs", sector: "Sustainable Healthcare", description: "Net zero medical scrubs with innovative textiles", photo: "/startups/102.jpeg" },
  { name: "Jamie Marshall", company: "Cognitive Ninja", sector: "Digital Mental Health", description: "Digital mental health access solution", photo: "/startups/103.jpeg" },
  { name: "Ibrahim Samaan", company: "Purifas", sector: "Healthcare Sustainability", description: "Recyclable hospital bed linen system", photo: "/startups/104.jpg" },
  { name: "Husayn Aly", company: "Corporate Mental Health App", sector: "Occupational Health", description: "Mobile app for corporate mental health", photo: "/startups/105.jpeg" },
  { name: "Gerard Hawthorn", company: "Locums Made Easy", sector: "HealthTech", description: "Locum clinician marketplace platform", photo: "/startups/106.jpg" },
  { name: "Errol Lim", company: "BJC Connect", sector: "Patient Support", description: "Online chronic disease community support", photo: "/startups/107.jpeg" },
  { name: "Emma Charters", company: "Speech Pathology Research", sector: "Head & Neck Health", description: "Speech pathology for head and neck cancer", photo: "/startups/108.png" },
  { name: "Emily Smith", company: "Podiatrist Insoles", sector: "Podiatry Tech", description: "Performance-engineered custom insoles", photo: "/startups/109.jpeg" },
  { name: "Ellen Downes", company: "Cancer Rehabilitation Services", sector: "Oncology Wellness", description: "Rural cancer survivorship and rehabilitation", photo: "/startups/110.jpg" },
  { name: "Elizabeth Jones", company: "beHub", sector: "Medical Device Education", description: "Hospital-device education and compliance platform", photo: "/startups/111.png" },
  { name: "Dilip Gahankari", company: "Plastic Surgery Innovation", sector: "Surgical Innovation", description: "Plastic surgery innovation and rural support", photo: "/startups/112.jpeg" },
  { name: "Dijana Dragicevich", company: "Sydney Swallowing Diagnostics", sector: "Diagnostics", description: "Mobile swallowing assessment technology", photo: "/startups/113.jpg" },
  { name: "Craig Haifer", company: "Faecal Microbiota Transplantation", sector: "Biotech / Gastro", description: "Microbial therapeutic development", photo: "/startups/114.png" },
  { name: "Clint Wilkie", company: "Health Hotels", sector: "Healthcare Services", description: "Hotel-based patient recovery care model", photo: "/startups/115.jpeg" },
  { name: "Claire Wu", company: "MiniME", sector: "Mental Health Support", description: "AI mental health companion app", photo: "/startups/116.jpeg" },
  { name: "Ciara Nuttall", company: "ClinicAlly", sector: "Patient Platform", description: "Symptom recording and medical report generation", photo: "/startups/117.jpg" },
  { name: "Christopher Chen", company: "Scuttle", sector: "Clinical Software", description: "Patient issue tracking and clinical handover", photo: "/startups/118.jpeg" },
  { name: "Chaturica Athukorala", company: "Aurabox", sector: "Admin Efficiency", description: "Medical professional admin task automation", photo: "/startups/119.jpeg" },
  { name: "Charlotte Mann", company: "Pal There", sector: "Palliative Care Platform", description: "Online palliative care education and monitoring", photo: "/startups/120.jpg" },
  { name: "Cathie Sherrington", company: "Evidence-based Fall Prevention", sector: "Public Health", description: "Falls prevention implementation at scale", photo: "/startups/121.jpg" },
  { name: "Casey Pfluger", company: "Cortex Technologies", sector: "Neurotechnology", description: "Non-invasive brain-computer interface headset", photo: "/startups/122.jpg" },
  { name: "Bruce Lo", company: "Locumist", sector: "HealthTech", description: "Locum doctor job opportunity platform", photo: "/startups/123.jpeg" },
  { name: "Bradley Chesham", company: "XR Healthcare Education", sector: "EdTech", description: "Immersive healthcare professional training", photo: "/startups/124.jpeg" },
  { name: "Benjamin Smoker", company: "Hospital Communication App", sector: "HealthTech", description: "Customizable patient-staff communication app", photo: "/startups/125.jpeg" },
  { name: "Aurora Warren", company: "AURORA", sector: "Care Coordination Platform", description: "Pediatric care coordination collaboration platform", photo: "/startups/126.jpg" },
  { name: "Andrew Fong", company: "Food Allergy Health Economics Model", sector: "Health Economics", description: "Food allergy pharmaceutical market optimization", photo: "/startups/127.jpg" },
  { name: "Amy Oman", company: "Explore Learn Move", sector: "Occupational Health", description: "Children's development and family support programs", photo: "/startups/128.png" },
  { name: "Alexander Holden", company: "Digital Dentistry Commercialization", sector: "Dental Tech", description: "Public oral health services digitization", photo: "/startups/129.jpeg" },
  { name: "Ajuni Chahal", company: "MedXsim", sector: "Healthcare Training", description: "AI-powered patient simulator for training", photo: "/startups/130.jpg" },
  { name: "Tim Inglis", company: "Sepsis Diagnostics Platform", sector: "Diagnostics", description: "Rapid sepsis diagnostic technology", photo: "/startups/131.jpeg" },
  { name: "Thomas Drake-Brockman", company: "RACUS", sector: "Pediatric Anesthesia", description: "Remote post-operative care via smartphone", photo: "/startups/132.jpeg" },
  { name: "Sarah Oorschot", company: "Parenteral Nutrition Model", sector: "Clinical Nutrition", description: "Intravenous nutrition support care model", photo: "/startups/133.jpeg" },
  { name: "Nicholas Buckley", company: "VeinWise", sector: "MedTech", description: "Intelligent vein identification and cannulation", photo: "/startups/134.jpeg" },
  { name: "Monica Hunter", company: "Pressure Prevention Program", sector: "Patient Care", description: "Chronic health condition quality of life improvement", photo: "/startups/135.jpeg" },
  { name: "Kevin Wernli", company: "Matilda", sector: "Women's Health Platform", description: "Digital endometriosis care platform", photo: "/startups/136.jpeg" },
  { name: "Joos Meyer", company: "One Right Eye", sector: "Patient Education", description: "3D digital eye model for patient education", photo: "/startups/137.jpeg" },
  { name: "Jaroslaw Hryniewicki", company: "VoiX", sector: "Youth Mental Health", description: "Digital platform for youth mental health support", photo: "/startups/138.jpeg" },
  { name: "Helen DeJong", company: "Skin Disorder Multimodal Imaging", sector: "Dermatology Tech", description: "Real-time skin disorder research and quantification", photo: "/startups/139.jpeg" },
  { name: "Harry Smallbone", company: "HistoAI", sector: "HealthTech / AI", description: "AI histopathology analysis platform", photo: "/startups/140.jpeg" },
  { name: "Hanh Nguyen", company: "LifeBerg", sector: "Life Management App", description: "Integrated productivity and health app", photo: "/startups/141.png" },
  { name: "Gabrielle Holt", company: "Schulte Holt Toric Processor", sector: "Ophthalmic Tech", description: "Cataract workflow optimization device", photo: "/startups/142.jpeg" },
  { name: "Evan Wong", company: "Corneal Endothelial Cell Therapy", sector: "Ophthalmic Biotech", description: "Cell therapy for corneal blindness treatment", photo: "/startups/143.jpeg" },
  { name: "Emily Zhen", company: "Organ & Tissue Transport Device", sector: "MedTech", description: "Active cooling organ transport system", photo: "/startups/144.jpeg" },
  { name: "Donnetta Charles", company: "Rubix Health", sector: "Chronic Pain Management", description: "Regional persistent pain care transformation", photo: "/startups/145.jpeg" },
  { name: "Collin Chin", company: "Place-of-care CAR T-cell Therapy", sector: "Oncology Biotech", description: "Manufactured CAR T-cell cancer therapy", photo: "/startups/146.png" },
  { name: "Claire Mullane", company: "Physiotherapy Innovation", sector: "Clinical Services", description: "Complex patient mobility and transfer solutions", photo: "/startups/147.jpeg" },
  { name: "Caitlin Hunt", company: "Exercise Physiology Access", sector: "Wellness Services", description: "Evidence-based exercise physiology care", photo: "/startups/148.jpeg" },
  { name: "Bronwyn Raykos", company: "Eating Disorders Waitlist Project", sector: "Mental Health Services", description: "Eating disorder treatment access acceleration", photo: "/startups/149.jpeg" },
  { name: "Anna Surla", company: "Relay", sector: "Hospital Operations", description: "Switchboard automation and referral management", photo: "/startups/150.png" },
  { name: "Amy Wallis", company: "Selsus", sector: "Oncology Support", description: "Cancer recovery and rehabilitation platform", photo: "/startups/151.png" },
  { name: "Abdul Rahman-Ihdayhid", company: "3D-Printed Polymeric Heart Valve", sector: "Cardiology Biotech", description: "Bioengineered heart valve development", photo: "/startups/152.jpeg" },
];
